<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cpu6502.Core\Cpu6502.Core.csproj" />
    <ProjectReference Include="..\..\src\Machines.Common\Machines.Common.csproj" />
    <ProjectReference Include="..\..\src\Machines.Atom\Machines.Atom.csproj" />
    <ProjectReference Include="..\..\src\Machines.Vic20\Machines.Vic20.csproj" />
    <ProjectReference Include="..\..\src\Machines.C64\Machines.C64.csproj" />
    <ProjectReference Include="..\..\src\Machines.Oric\Machines.Oric.csproj" />
    <ProjectReference Include="..\..\src\Machines.Pet\Machines.Pet.csproj" />
    <ProjectReference Include="..\..\src\Machines.BbcMicro\Machines.BbcMicro.csproj" />
    <ProjectReference Include="..\..\src\Machines.BbcMaster\Machines.BbcMaster.csproj" />
  </ItemGroup>

</Project>
