<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cpu6502.Core\Cpu6502.Core.csproj" />
    <ProjectReference Include="..\..\src\Machines.Atari800\Machines.Atari800.csproj" />
    <ProjectReference Include="..\..\src\Machines.Common\Machines.Common.csproj" />
  </ItemGroup>

</Project>
